/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.26.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  hub: string;
  pair: string;
}
export type ExecuteMsg = {
  bond: {};
};
export type QueryMsg = {
  config: {};
} | {
  simulate: {
    bond: Uint128;
  };
};
export type Uint128 = string;
export interface MigrateMsg {
  [k: string]: unknown;
}
export interface ConfigResponse {
  bond_denom: string;
  hub: string;
  lsd_token: string;
  pair: string;
}
export interface SimulateResponse {
  lsd_val: Uint128;
}