/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export type PairType =
  | {
      xyk: {};
    }
  | {
      stable: {};
    }
  | {
      custom: string;
    };
export interface InstantiateMsg {
  fee_address?: string | null;
  owner: string;
  pair_configs: PairConfig[];
  token_code_id: number;
}
export interface PairConfig {
  code_id: number;
  is_disabled: boolean;
  maker_fee_bps: number;
  pair_type: PairType;
  total_fee_bps: number;
}
export type ExecuteMsg =
  | {
      update_config: {
        fee_address?: string | null;
        token_code_id?: number | null;
      };
    }
  | {
      update_pair_config: {
        config: PairConfig;
      };
    }
  | {
      create_pair: {
        asset_infos: AssetInfo[];
        init_params?: Binary | null;
        pair_type: PairType;
      };
    }
  | {
      deregister: {
        asset_infos: AssetInfo[];
      };
    }
  | {
      propose_new_owner: {
        expires_in: number;
        owner: string;
      };
    }
  | {
      drop_ownership_proposal: {};
    }
  | {
      claim_ownership: {};
    }
  | {
      mark_as_migrated: {
        pairs: string[];
      };
    };
export type AssetInfo =
  | {
      token: string;
    }
  | {
      native_token: string;
    };
export type Binary = string;
export type QueryMsg =
  | {
      config: {};
    }
  | {
      pair: {
        asset_infos: AssetInfo[];
      };
    }
  | {
      pairs: {
        limit?: number | null;
        start_after?: AssetInfo[] | null;
      };
    }
  | {
      fee_info: {
        pair_type: PairType;
      };
    }
  | {
      blacklisted_pair_types: {};
    }
  | {
      pairs_to_migrate: {};
    };
export type ArrayOfPairType = PairType[];
export type Addr = string;
export interface ConfigResponse {
  fee_address?: Addr | null;
  owner: Addr;
  pair_configs: PairConfig[];
  token_code_id: number;
}
export interface FeeInfoResponse {
  fee_address?: Addr | null;
  maker_fee_bps: number;
  total_fee_bps: number;
}
export type AssetInfoValidated =
  | {
      token: Addr;
    }
  | {
      native_token: string;
    };
export interface PairInfo {
  asset_infos: AssetInfoValidated[];
  contract_addr: Addr;
  liquidity_token: Addr;
  pair_type: PairType;
}
export interface PairsResponse {
  pairs: PairInfo[];
}
export type ArrayOfAddr = Addr[];
