/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { selectorFamily } from "recoil";
import { cosmWasmStargateClientSelector as cosmWasmClient } from "../chain";
import {
  Uint128,
  ConfigResponse,
  CumulativePricesResponse,
  PairInfo,
  PoolResponse,
  ArrayOfAssetValidated,
  SimulationResponse,
  ReverseSimulationResponse,
} from "../../../clients/types/WyndexPair.types";
import { WyndexPairClient, WyndexPairQueryClient } from "../../../clients/WyndexPair.client";
import { signingCosmWasmStargateClientAtom } from "../../atoms";

type QueryClientParams = {
  contractAddress: string;
};
export const queryClient = selectorFamily<WyndexPairQueryClient, QueryClientParams>({
  key: "wyndexPairQueryClient",
  get:
    ({ contractAddress }) =>
    ({ get }) => {
      const client = get(cosmWasmClient);
      return new WyndexPairQueryClient(client, contractAddress);
    },
});

export type ExecuteClientParams = {
  contractAddress: string;
  sender: string;
};

export const executeClient = selectorFamily<WyndexPairClient | undefined, ExecuteClientParams>({
  key: "wyndexPairExecuteClient",
  get:
    ({ contractAddress, sender }) =>
    ({ get }) => {
      const client = get(signingCosmWasmStargateClientAtom);
      if (!client) return;
      return new WyndexPairClient(client, sender, contractAddress);
    },
  dangerouslyAllowMutability: true,
});

export const pairSelector = selectorFamily<
  PairInfo,
  QueryClientParams & {
    params: Parameters<WyndexPairQueryClient["pair"]>;
  }
>({
  key: "wyndexPairPair",
  get:
    ({ params, ...queryClientParams }) =>
    async ({ get }) => {
      const client = get(queryClient(queryClientParams));
      return await client.pair(...params);
    },
});
export const poolSelector = selectorFamily<
  PoolResponse,
  QueryClientParams & {
    params: Parameters<WyndexPairQueryClient["pool"]>;
  }
>({
  key: "wyndexPairPool",
  get:
    ({ params, ...queryClientParams }) =>
    async ({ get }) => {
      const client = get(queryClient(queryClientParams));
      return await client.pool(...params);
    },
});
export const configSelector = selectorFamily<
  ConfigResponse,
  QueryClientParams & {
    params: Parameters<WyndexPairQueryClient["config"]>;
  }
>({
  key: "wyndexPairConfig",
  get:
    ({ params, ...queryClientParams }) =>
    async ({ get }) => {
      const client = get(queryClient(queryClientParams));
      return await client.config(...params);
    },
});
export const shareSelector = selectorFamily<
  ArrayOfAssetValidated,
  QueryClientParams & {
    params: Parameters<WyndexPairQueryClient["share"]>;
  }
>({
  key: "wyndexPairShare",
  get:
    ({ params, ...queryClientParams }) =>
    async ({ get }) => {
      const client = get(queryClient(queryClientParams));
      return await client.share(...params);
    },
});
export const simulationSelector = selectorFamily<
  SimulationResponse,
  // @ts-ignore
  QueryClientParams & {
    params: Parameters<WyndexPairQueryClient["simulation"]>;
  }
>({
  key: "wyndexPairSimulation",
  get:
    ({ params, ...queryClientParams }) =>
    async ({ get }) => {
      const client = get(queryClient(queryClientParams));
      return await client.simulation(...params);
    },
});
export const reverseSimulationSelector = selectorFamily<
  ReverseSimulationResponse,
  // @ts-ignore
  QueryClientParams & {
    params: Parameters<WyndexPairQueryClient["reverseSimulation"]>;
  }
>({
  key: "wyndexPairReverseSimulation",
  get:
    ({ params, ...queryClientParams }) =>
    async ({ get }) => {
      const client = get(queryClient(queryClientParams));
      return await client.reverseSimulation(...params);
    },
});
export const cumulativePricesSelector = selectorFamily<
  CumulativePricesResponse,
  QueryClientParams & {
    params: Parameters<WyndexPairQueryClient["cumulativePrices"]>;
  }
>({
  key: "wyndexPairCumulativePrices",
  get:
    ({ params, ...queryClientParams }) =>
    async ({ get }) => {
      const client = get(queryClient(queryClientParams));
      return await client.cumulativePrices(...params);
    },
});
export const queryComputeDSelector = selectorFamily<
  Uint128,
  QueryClientParams & {
    params: Parameters<WyndexPairQueryClient["queryComputeD"]>;
  }
>({
  key: "wyndexPairQueryComputeD",
  get:
    ({ params, ...queryClientParams }) =>
    async ({ get }) => {
      const client = get(queryClient(queryClientParams));
      return await client.queryComputeD(...params);
    },
});
