export const CHAIN_RPC_ENDPOINT = process.env.NEXT_PUBLIC_CHAIN_RPC_ENDPOINT || "";
export const CHAIN_NAME = process.env.NEXT_PUBLIC_CHAIN_NAME || "";
export const FACTORY_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_FACTORY_CONTRACT_ADDRESS || "";
export const MULTI_HOP_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_MULTI_HOP_CONTRACT_ADDRESS || "";
export const REST_API_ENDPOINT = process.env.NEXT_PUBLIC_REST_API_ENDPOINT || "";
export const EXPLORER_URL = process.env.NEXT_PUBLIC_EXPLORER_URL || "";
export const INDEXER_API_ENDPOINT = process.env.NEXT_PUBLIC_INDEXER_API_ENDPOINT || "";
