/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { Coin, StdFee } from "@cosmjs/amino";
import { CosmWasmClient, ExecuteResult, SigningCosmWasmClient } from "@cosmjs/cosmwasm-stargate";

import {
  AdminResponse,
  AllStakedResponse,
  Binary,
  BondingInfoResponse,
  ClaimsResponse,
  DelegatedResponse,
  DistributedRewardsResponse,
  DistributionDataResponse,
  HooksResponse,
  InfoResponse,
  RewardsResponse,
  StakedResponse,
  TokenContractResponse,
  TotalPowerAtHeightResponse,
  TotalRewardsResponse,
  TotalStakedResponse,
  TotalUnbondingResponse,
  Uint128,
  UndistributedRewardsResponse,
  VotingPowerAtHeightResponse,
  WithdrawAdjustmentDataResponse,
  WithdrawableRewardsResponse,
} from "./types/WyndDaoStake.types";
export interface WyndStakeReadOnlyInterface {
  contractAddress: string;
  claims: ({ address }: { address: string }) => Promise<ClaimsResponse>;
  staked: ({
    address,
    unbondingPeriod,
  }: {
    address: string;
    unbondingPeriod: number;
  }) => Promise<StakedResponse>;
  allStaked: ({ address }: { address: string }) => Promise<AllStakedResponse>;
  totalStaked: () => Promise<TotalStakedResponse>;
  totalUnbonding: () => Promise<TotalUnbondingResponse>;
  totalRewards: () => Promise<TotalRewardsResponse>;
  rewards: ({ address }: { address: string }) => Promise<RewardsResponse>;
  admin: () => Promise<AdminResponse>;
  hooks: () => Promise<HooksResponse>;
  bondingInfo: () => Promise<BondingInfoResponse>;
  withdrawableRewards: ({ owner }: { owner: string }) => Promise<WithdrawableRewardsResponse>;
  distributedRewards: () => Promise<DistributedRewardsResponse>;
  undistributedRewards: () => Promise<UndistributedRewardsResponse>;
  delegated: ({ owner }: { owner: string }) => Promise<DelegatedResponse>;
  distributionData: () => Promise<DistributionDataResponse>;
  withdrawAdjustmentData: ({ addr }: { addr: string }) => Promise<WithdrawAdjustmentDataResponse>;
  votingPowerAtHeight: ({
    address,
    height,
  }: {
    address: string;
    height?: number;
  }) => Promise<VotingPowerAtHeightResponse>;
  totalPowerAtHeight: ({ height }: { height?: number }) => Promise<TotalPowerAtHeightResponse>;
  info: () => Promise<InfoResponse>;
  tokenContract: () => Promise<TokenContractResponse>;
}
export class WyndStakeQueryClient implements WyndStakeReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.claims = this.claims.bind(this);
    this.staked = this.staked.bind(this);
    this.allStaked = this.allStaked.bind(this);
    this.totalStaked = this.totalStaked.bind(this);
    this.totalUnbonding = this.totalUnbonding.bind(this);
    this.totalRewards = this.totalRewards.bind(this);
    this.rewards = this.rewards.bind(this);
    this.admin = this.admin.bind(this);
    this.hooks = this.hooks.bind(this);
    this.bondingInfo = this.bondingInfo.bind(this);
    this.withdrawableRewards = this.withdrawableRewards.bind(this);
    this.distributedRewards = this.distributedRewards.bind(this);
    this.undistributedRewards = this.undistributedRewards.bind(this);
    this.delegated = this.delegated.bind(this);
    this.distributionData = this.distributionData.bind(this);
    this.withdrawAdjustmentData = this.withdrawAdjustmentData.bind(this);
    this.votingPowerAtHeight = this.votingPowerAtHeight.bind(this);
    this.totalPowerAtHeight = this.totalPowerAtHeight.bind(this);
    this.info = this.info.bind(this);
    this.tokenContract = this.tokenContract.bind(this);
  }

  claims = async ({ address }: { address: string }): Promise<ClaimsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      claims: {
        address,
      },
    });
  };
  staked = async ({
    address,
    unbondingPeriod,
  }: {
    address: string;
    unbondingPeriod: number;
  }): Promise<StakedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      staked: {
        address,
        unbonding_period: unbondingPeriod,
      },
    });
  };
  allStaked = async ({ address }: { address: string }): Promise<AllStakedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_staked: {
        address,
      },
    });
  };
  totalStaked = async (): Promise<TotalStakedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      total_staked: {},
    });
  };
  totalUnbonding = async (): Promise<TotalUnbondingResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      total_unbonding: {},
    });
  };
  totalRewards = async (): Promise<TotalRewardsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      total_rewards: {},
    });
  };
  rewards = async ({ address }: { address: string }): Promise<RewardsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      rewards: {
        address,
      },
    });
  };
  admin = async (): Promise<AdminResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      admin: {},
    });
  };
  hooks = async (): Promise<HooksResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      hooks: {},
    });
  };
  bondingInfo = async (): Promise<BondingInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      bonding_info: {},
    });
  };
  withdrawableRewards = async ({ owner }: { owner: string }): Promise<WithdrawableRewardsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      withdrawable_rewards: {
        owner,
      },
    });
  };
  distributedRewards = async (): Promise<DistributedRewardsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      distributed_rewards: {},
    });
  };
  undistributedRewards = async (): Promise<UndistributedRewardsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      undistributed_rewards: {},
    });
  };
  delegated = async ({ owner }: { owner: string }): Promise<DelegatedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      delegated: {
        owner,
      },
    });
  };
  distributionData = async (): Promise<DistributionDataResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      distribution_data: {},
    });
  };
  withdrawAdjustmentData = async ({ addr }: { addr: string }): Promise<WithdrawAdjustmentDataResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      withdraw_adjustment_data: {
        addr,
      },
    });
  };
  votingPowerAtHeight = async ({
    address,
    height,
  }: {
    address: string;
    height?: number;
  }): Promise<VotingPowerAtHeightResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      voting_power_at_height: {
        address,
        height,
      },
    });
  };
  totalPowerAtHeight = async ({ height }: { height?: number }): Promise<TotalPowerAtHeightResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      total_power_at_height: {
        height,
      },
    });
  };
  info = async (): Promise<InfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      info: {},
    });
  };
  tokenContract = async (): Promise<TokenContractResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      token_contract: {},
    });
  };
}
export interface WyndStakeInterface extends WyndStakeReadOnlyInterface {
  contractAddress: string;
  sender: string;
  rebond: (
    {
      bondFrom,
      bondTo,
      tokens,
    }: {
      bondFrom: number;
      bondTo: number;
      tokens: Uint128;
    },
    fee?: number | StdFee | "auto",
    memo?: string,
    funds?: Coin[],
  ) => Promise<ExecuteResult>;
  unbond: (
    {
      tokens,
      unbondingPeriod,
    }: {
      tokens: Uint128;
      unbondingPeriod: number;
    },
    fee?: number | StdFee | "auto",
    memo?: string,
    funds?: Coin[],
  ) => Promise<ExecuteResult>;
  claim: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  updateAdmin: (
    {
      admin,
    }: {
      admin?: string;
    },
    fee?: number | StdFee | "auto",
    memo?: string,
    funds?: Coin[],
  ) => Promise<ExecuteResult>;
  addHook: (
    {
      addr,
    }: {
      addr: string;
    },
    fee?: number | StdFee | "auto",
    memo?: string,
    funds?: Coin[],
  ) => Promise<ExecuteResult>;
  removeHook: (
    {
      addr,
    }: {
      addr: string;
    },
    fee?: number | StdFee | "auto",
    memo?: string,
    funds?: Coin[],
  ) => Promise<ExecuteResult>;
  receiveDelegation: (
    {
      amount,
      msg,
      sender,
    }: {
      amount: Uint128;
      msg: Binary;
      sender: string;
    },
    fee?: number | StdFee | "auto",
    memo?: string,
    funds?: Coin[],
  ) => Promise<ExecuteResult>;
  distributeRewards: (
    {
      sender,
    }: {
      sender?: string;
    },
    fee?: number | StdFee | "auto",
    memo?: string,
    funds?: Coin[],
  ) => Promise<ExecuteResult>;
  withdrawRewards: (
    {
      owner,
      receiver,
    }: {
      owner?: string;
      receiver?: string;
    },
    fee?: number | StdFee | "auto",
    memo?: string,
    funds?: Coin[],
  ) => Promise<ExecuteResult>;
  delegateWithdrawal: (
    {
      delegated,
    }: {
      delegated: string;
    },
    fee?: number | StdFee | "auto",
    memo?: string,
    funds?: Coin[],
  ) => Promise<ExecuteResult>;
}
export class WyndStakeClient extends WyndStakeQueryClient implements WyndStakeInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.rebond = this.rebond.bind(this);
    this.unbond = this.unbond.bind(this);
    this.claim = this.claim.bind(this);
    this.updateAdmin = this.updateAdmin.bind(this);
    this.addHook = this.addHook.bind(this);
    this.removeHook = this.removeHook.bind(this);
    this.receiveDelegation = this.receiveDelegation.bind(this);
    this.distributeRewards = this.distributeRewards.bind(this);
    this.withdrawRewards = this.withdrawRewards.bind(this);
    this.delegateWithdrawal = this.delegateWithdrawal.bind(this);
  }

  rebond = async (
    {
      bondFrom,
      bondTo,
      tokens,
    }: {
      bondFrom: number;
      bondTo: number;
      tokens: Uint128;
    },
    fee: number | StdFee | "auto" = "auto",
    memo?: string,
    funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        rebond: {
          bond_from: bondFrom,
          bond_to: bondTo,
          tokens,
        },
      },
      fee,
      memo,
      funds,
    );
  };
  unbond = async (
    {
      tokens,
      unbondingPeriod,
    }: {
      tokens: Uint128;
      unbondingPeriod: number;
    },
    fee: number | StdFee | "auto" = "auto",
    memo?: string,
    funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        unbond: {
          tokens,
          unbonding_period: unbondingPeriod,
        },
      },
      fee,
      memo,
      funds,
    );
  };
  claim = async (
    fee: number | StdFee | "auto" = "auto",
    memo?: string,
    funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        claim: {},
      },
      fee,
      memo,
      funds,
    );
  };
  updateAdmin = async (
    {
      admin,
    }: {
      admin?: string;
    },
    fee: number | StdFee | "auto" = "auto",
    memo?: string,
    funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        update_admin: {
          admin,
        },
      },
      fee,
      memo,
      funds,
    );
  };
  addHook = async (
    {
      addr,
    }: {
      addr: string;
    },
    fee: number | StdFee | "auto" = "auto",
    memo?: string,
    funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        add_hook: {
          addr,
        },
      },
      fee,
      memo,
      funds,
    );
  };
  removeHook = async (
    {
      addr,
    }: {
      addr: string;
    },
    fee: number | StdFee | "auto" = "auto",
    memo?: string,
    funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        remove_hook: {
          addr,
        },
      },
      fee,
      memo,
      funds,
    );
  };
  receiveDelegation = async (
    {
      amount,
      msg,
      sender,
    }: {
      amount: Uint128;
      msg: Binary;
      sender: string;
    },
    fee: number | StdFee | "auto" = "auto",
    memo?: string,
    funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        receive_delegation: {
          amount,
          msg,
          sender,
        },
      },
      fee,
      memo,
      funds,
    );
  };
  distributeRewards = async (
    {
      sender,
    }: {
      sender?: string;
    },
    fee: number | StdFee | "auto" = "auto",
    memo?: string,
    funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        distribute_rewards: {
          sender,
        },
      },
      fee,
      memo,
      funds,
    );
  };
  withdrawRewards = async (
    {
      owner,
      receiver,
    }: {
      owner?: string;
      receiver?: string;
    },
    fee: number | StdFee | "auto" = "auto",
    memo?: string,
    funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        withdraw_rewards: {
          owner,
          receiver,
        },
      },
      fee,
      memo,
      funds,
    );
  };
  delegateWithdrawal = async (
    {
      delegated,
    }: {
      delegated: string;
    },
    fee: number | StdFee | "auto" = "auto",
    memo?: string,
    funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        delegate_withdrawal: {
          delegated,
        },
      },
      fee,
      memo,
      funds,
    );
  };
}
