name: Checks
on: push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env: # Squid Router
      NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn lint
  build:
    name: Build
    runs-on: ubuntu-latest
    env: # Squid Router
      NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: mv .env.example .env
      - run: yarn build
